### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by angelazerbi** [LeoBPol/LabSession6#1]
Bonjour Léo, 
Je n'ai pu m'empêcher de remarquer que vous aviez enlevé la ligne TRES IMPORTANTE que j'avais rajoutée dans le fichier MANIFEST.txt ...
Je dois vous avouer que je suis **extrêmement déçue.......**

**Comment by LeoBPol** [comment]
Bonjour Angela,
Cela doit être une **malencontreuse** erreur. Je suis attristé de voir que vous m'en teniez rigueur. Je retiens votre message....

**Comment by LeoBPol** [comment]
C'est une honte

**Comment by LeoBPol** [comment]
**HONTEUX**

**Comment by angelazerbi** [comment]
ok je retiens également
